### ISSUE TITLE
why

### ISSUE THREAD

**Issue by jshdm** [Cryptoc1/hiroshima#1]

**Comment by Cryptoc1** [comment]
Bored, mostly. Also thought it would be a fun way to learn OAuth concepts.

**Comment by jshdm** [comment]
fair game :sunglasses:

**Comment by Cryptoc1** [comment]
Oh, and love messing with people. trololololol.jpeg

**Comment by jshdm** [comment]
![screen shot 2015-04-12 at 11 10 07 pm](https://cloud.githubusercontent.com/assets/4617414/7110575/185a8ebe-e169-11e4-9205-4d09fc10f2a6.png)

**Comment by Cryptoc1** [comment]
![image](https://cloud.githubusercontent.com/assets/6041110/7110599/9443f420-e182-11e4-8f15-2a4c748693e0.png)
